services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bytix-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    networks:
      - bytix-network

  nginx:
    image: nginx:alpine
    container_name: bytix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-bytix.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - bytix-network
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: bytix-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - bytix-network

networks:
  bytix-network:
    driver: bridge
